### PR TITLE
remove the note_data

### PR DESCRIPTION
**Pull request by XuyangSong**
> To keep notes lightweight, we aim to encode any arbitrary data inside app_data and app_data_dynamic and the encoding mechanisms are application dependent, so we don't need note_data.

### CODE REVIEW

**Comment by Acentelles** [comment]
Can you also update the examples?

**Comment by Acentelles** [comment]
For future reference, it's worth noting the reason of this PR. I believe that we try to keep notes lightweight and we aim to encode any arbitrary data inside `app_data` and `app_data_dynamic` and the encoding mechanisms are application dependent, so we don't need `note_data`. Is this correct @XuyangSong ?

**Comment by bazzilic** [comment]
If I remember our discussion on this correctly, we model two layers of "indirection": notes are stored separately, off chain; and to keep them lightweight, whatever data is attached to the note, that is _also_ stored separately, and the note only keeps some kind of reference to that data. Does my memory serve me right? If so, where is that reference kept in the note?

**Review by Acentelles — APPROVED** [review]

**Comment by Acentelles** [comment]
I think that the reference for the data attached to the note that you mention is what is stored in `app_data` and `app_data_dynamic`

**Pull request merged**
